# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include: [master]# branch names which will trigger a build
    # exclude: [ string ] # branch names which will not
  tags:
    include: [build_pipeline]

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build_Server
    displayName: Prepare build environment
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.14.2'
      displayName: 'Install Node.js'
    
   
    - script: |
        npm install i -g @ionic/cli
        npm install i -g @angular/cli
        npm install
        ionic build --prod
      displayName: 'ionic install and build'


    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/www'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
          targetPath: '$(Pipeline.Workspace)/a'
          publishLocation: 'pipeline'